name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    tags:
      - “v*.*.*”
  pull_request:
    branches:
      - main
      - dev
jobs:
  client-checks:
    name: Client Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean Up
        run: rm ../../package.json
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ‘**/node_modules’
          key: ${{ runner.os }}-node-client-${{ hashFiles(‘**/package-lock.json’) }}
          restore-keys: |
            ${{ runner.os }}-node-client-
      - name: Install dependencies
        run: npm install
      - name: Check Formatting
        run: npm run prettier
  server-checks:
    name: Server Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Clean Up
        run: rm ../../package.json
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ‘**/node_modules’
          key: ${{ runner.os }}-node-server-${{ hashFiles(‘**/package-lock.json’) }}
          restore-keys: |
            ${{ runner.os }}-node-server-
      - name: Install dependencies
        run: |
          npm install
          npm run prisma:generate
      - name: Check Formatting
        run: npm run prettier
      - name: Check Linting
        run: npm run lint
      - name: Tests
        continue-on-error: true
        run: npm run test:cov
